In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\\prava\\Downloads\\bmi.csv")

In [3]:
data.head()

Country  Life expectancy       BMI
0  Afghanistan             52.8  20.62058
1      Albania             76.8  26.44657
2      Algeria             75.5  24.59620
3      Andorra             84.6  27.63048
4       Angola             56.7  22.25083

In [4]:
X = np.array(data.iloc[:, :-1])

In [6]:
X[:5]

array([['Afghanistan', 52.8],
       ['Albania', 76.8],
       ['Algeria', 75.5],
       ['Andorra', 84.6],
       ['Angola', 56.7]], dtype=object)

In [7]:
X.shape

(163, 2)

In [11]:
y = np.array(data['BMI'])

In [12]:
y[:5]

array([20.62058, 26.44657, 24.5962 , 27.63048, 22.25083])

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
bmi_model = LinearRegression()

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 0, test_size = 0.2)

In [18]:
X_train.shape

(130, 2)

In [19]:
y_train.shape

(130,)

In [23]:
bmi_model.fit(X_train[:, 1].reshape(-1,1), y_train)

LinearRegression()

In [24]:
bmi_model.predict([[21.07931]])

array([16.1563578])

In [25]:
y_pred = bmi_model.predict(X_test[:,1].reshape(-1,1))

In [30]:
np.concatenate((y_pred.reshape(-1,1), y_test.reshape(-1,1)), axis = 1)

array([[25.51092144, 20.9163    ],
       [26.16372104, 26.70371   ],
       [26.65773155, 27.13151   ],
       [26.62244509, 26.46741   ],
       [25.36977557, 25.63182   ],
       [25.10512709, 25.54942   ],
       [23.64073878, 21.92743   ],
       [25.4403485 , 26.36751   ],
       [26.69301802, 27.4521    ],
       [26.28722367, 23.21991   ],
       [24.82283537, 25.49887   ],
       [24.41704102, 22.62295   ],
       [21.71762644, 21.96917   ],
       [25.21098648, 26.45693   ],
       [21.89405876, 21.64338   ],
       [26.18136427, 28.13138   ],
       [25.88142932, 26.59629   ],
       [26.49894246, 27.39249   ],
       [21.96463169, 21.93536   ],
       [23.09379858, 22.47792   ],
       [25.68911808, 30.86752   ],
       [26.74594771, 26.37629   ],
       [22.58214483, 19.86692   ],
       [23.04086888, 20.88509   ],
       [24.8404786 , 30.99563   ],
       [24.64640304, 25.65117   ],
       [24.29353839, 25.24796   ],
       [25.58149437, 24.73069   ],
       [26.67537478,

In [28]:
y_pred

array([25.51092144, 26.16372104, 26.65773155, 26.62244509, 25.36977557,
       25.10512709, 23.64073878, 25.4403485 , 26.69301802, 26.28722367,
       24.82283537, 24.41704102, 21.71762644, 25.21098648, 21.89405876,
       26.18136427, 25.88142932, 26.49894246, 21.96463169, 23.09379858,
       25.68911808, 26.74594771, 22.58214483, 23.04086888, 24.8404786 ,
       24.64640304, 24.29353839, 25.58149437, 26.67537478, 24.0818196 ,
       23.90538727, 26.55187216, 23.95831697])

In [29]:
y_test

array([20.9163 , 26.70371, 27.13151, 26.46741, 25.63182, 25.54942,
       21.92743, 26.36751, 27.4521 , 23.21991, 25.49887, 22.62295,
       21.96917, 26.45693, 21.64338, 28.13138, 26.59629, 27.39249,
       21.93536, 22.47792, 30.86752, 26.37629, 19.86692, 20.88509,
       30.99563, 25.65117, 25.24796, 24.73069, 27.68361, 23.51233,
       23.68465, 27.16509, 29.37337])

In [32]:
from sklearn.metrics import mean_squared_error

In [33]:
mean_squared_error(y_test, y_pred)

4.761630262960116